spring.application.name=StaffSphereWorkforce
server.port=8080


# Database Configuration (MySQL)

#Local Server db
spring.datasource.url=jdbc:mysql://localhost:3306/staffspheredb
spring.datasource.username=root
spring.datasource.password=Pavithra@2

#aivan cloud db
#spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}


# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# JSON Settings

spring.jackson.serialization.fail-on-empty-beans=false



# emui hwwu mzya qvxx

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bantupalli302@gmail.com
spring.mail.password=ilzfhwqjqwewbqfv

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#FRONTEND_URLS=http://localhost:5173